import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import SessionProvider from "@/components/SessionProvider";
import { ThemeProvider } from "next-themes";
import { ToastContainer } from "react-toastify";
import { cn } from "@/lib/utils";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background text-foreground",
          "scrollbar flex overflow-x-hidden",
          "lg:text-base"
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="flex flex-1 flex-col">
              {children}
              <ToastContainer
                position="top-center"
                autoClose={3000}
                closeOnClick
                pauseOnFocusLoss={true}
                theme="light"
              />
            </main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
